remove instance_type parameter in renew_task
swanchain/python-swan-sdk pull request #56
Opened 2024-09-05 17:59 UTC by alphaflows

2024-09-05 18:02 UTC, alphaflows commented
- remove `instance_type` parameter requirement in `renew_task`, `renew_payment`, `submit_payment` functions in orchestrator

2024-09-06 14:17 UTC, alphaflows commented
- remove `repo_name`, `repo_owner`, `repo_branch` parameters
- change `auto_pay` default to True to simplify logic
- add `INFO - Logging in Testnet/Mainnet` log info

2024-09-06 15:04 UTC, PlutoNbai requested changes

2024-09-06 15:04 UTC, PlutoNbai commented on swan/api/orchestrator.py
> +            auto_pay: (required True if no tx_hash but with private_key provided)
Consider removing this, auto_pay should be true

2024-09-06 15:04 UTC, PlutoNbai commented on swan/session.py
> +            logging.info("Logging in Mainnet")
Can you double check if you remove the logs when user logged in, as a user, I don't wanna see this log twice

2024-09-10 02:56 UTC, sonic-chain commented on docs/key_functions.md
> +  auto_pay = True,
You can delete `auto_pay`. If `private_key` has a value, it means automatic payment.

2024-09-10 05:51 UTC, sonic-chain commented on swan/api/orchestrator.py
> +    def submit_payment(self, task_uuid, private_key, duration = 3600, **kwargs):
Only supports automatic payment ？I don't see the manual payment function.

2024-09-10 18:28 UTC, alphaflows commented
add `repo_branch` back

2024-09-11 10:37 UTC, Normalnoise commented on docs/key_functions.md
> +- **repo_uri** (string) - The The URI of the repo to be deployed. The repository must contain a dockerfile. Please see [repo_uri](repo_uri.md)
- repo_uri: The repository must contain a `Dockerfile` or `deploy.yaml`; if there are `Dockerfile` or `deploy.yaml` in the repo, your project will be deployed by `deploy.yaml`, `Dockerfile ` will be ignored

 - `deploy.yaml` must be written according to [LDL specifications](https://docs.lagrangedao.org/spaces/intro/lagrange-definition-language-ldl)

2024-09-16 19:25 UTC, merged